version: '3.8'
services:
  web:
    build: .
    container_name: online-banking-web
    ports:
      - "80:80"
    volumes:
      - ./online-banking:/var/www/html/online-banking
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: online-banking-db
    restart: always
    environment:
      MYSQL_DATABASE: bank_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: online-banking-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
  
volumes:
  db_data:
